services:
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - trip-network
    env_file:
      - ./front/.env

  backend:
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - PYTHONPATH=/app
      - AUTH0_DOMAIN=duckgeunpark.us.auth0.com
      - AUTH0_AUDIENCE=https://duckgeunpark.us.auth0.com/api/v2/
    networks:
      - trip-network
    env_file:
      - ./back/.env

networks:
  trip-network:
    driver: bridge 