services:
  frontend:
    build: ./front
    container_name: iwt-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - iwt-network
    restart: unless-stopped

  backend:
    build: ./back
    container_name: iwt-backend
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - PYTHONPATH=/app
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    networks:
      - iwt-network
    restart: unless-stopped

networks:
  iwt-network:
    driver: bridge
    name: iwt-network 